version: "3.3"

services:
  backend:
    image: gitlab.praktikum-services.ru:5050/std-009-047/sausage-store/sausage-backend:latest
    container_name: sausage-backend
    env_file:
      - .backend.env
    networks:
      - sausage_network
      
  backend-report:
    image: gitlab.praktikum-services.ru:5050/std-009-047/sausage-store/sausage-report:latest
    container_name: sausage-report
    env_file:
      - .backend.report.env
    networks:
      - sausage_network

  frontend:
    image: gitlab.praktikum-services.ru:5050/std-009-047/sausage-store/sausage-frontend:latest
    container_name: sausage-frontend
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/app/nginx.tmpl
    environment:
      - DEFAULT_HOST=sausage-backend
    networks:
      - sausage_network

  networks:
    sausage_network:
      driver: bridge